version: '3'

services:
  binance:
    image: binancelaunchpadnotify
    container_name: binancelaunchpadnotify
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    env_file: .env
    restart: unless-stopped
