version: '3'

services:
  binance:
    image: binancelauchpadnotify
    container_name: binancelauchpadnotify
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    env_file: .env
    restart: unless-stopped